### ISSUE TITLE
Exponent Function Crashes on non-integer exponents

### ISSUE THREAD

**Issue by sultancillo** [at-import/Sassy-math#4]
exponent(20, $pi) will crash...

**Comment by Snugug** [comment]
Yes. We need to figure out a way to deal w/non integer exponents.
http://answers.yahoo.com/question/index?qid=20071004080918AAUlPW3
We're going to need to write ln function as well.

**Comment by scottkellum** [comment]
This would help simplify (and speed up) root calculations

``` sass
@function n-root($number, $n)
  +exponent($number, (1/$n))
```

**Comment by Snugug** [comment]
Is what we're doing in there is faster than what we're doing in n-root? Also don't know what we're actually doing for fractional exponents.
The bigger issue we have with that is exponents still don't work because I haven't figured out log/ln yet

EDIT: Didn't you see you said would help instead of a question.

**Comment by scottkellum** [comment]
Currently, n-root is essentially a pragmatic version of the guess and check method. Simple markup but it cuts a lot of corners at the cost of performance.

**Comment by Snugug** [comment]
Oh, well in that case, assuming that our fractional exponent stuff works, I'm all for it (I haven't looked at it).

**Comment by Snugug** [comment]
Update your gem to the 1.0 gem, totally rewritten from the ground up. This is now fixed.
